// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSPeConTI.BackEndBase.Services.CatalogoMateriales.Infrastructure;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CatalogoMaterialesContext))]
    [Migration("20220602195537_SegundaMigracion")]
    partial class SegundaMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("OSPeConTI.BackEndBase.Services.CatalogoMateriales.Domain.Entities.Clasificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clasificaciones", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.BackEndBase.Services.CatalogoMateriales.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ClasificacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdTipoMaterial")
                        .HasColumnType("int");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClasificacionId");

                    b.ToTable("Materiales", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.BackEndBase.Services.CatalogoMateriales.Domain.Entities.TipoMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<Guid?>("TipoMaterialesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TipoMaterialesId");

                    b.ToTable("TipoMateriales", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.BackEndBase.Services.CatalogoMateriales.Domain.Entities.Material", b =>
                {
                    b.HasOne("OSPeConTI.BackEndBase.Services.CatalogoMateriales.Domain.Entities.Clasificacion", "Clasificacion")
                        .WithMany()
                        .HasForeignKey("ClasificacionId");

                    b.Navigation("Clasificacion");
                });

            modelBuilder.Entity("OSPeConTI.BackEndBase.Services.CatalogoMateriales.Domain.Entities.TipoMaterial", b =>
                {
                    b.HasOne("OSPeConTI.BackEndBase.Services.CatalogoMateriales.Domain.Entities.TipoMaterial", "TipoMateriales")
                        .WithMany()
                        .HasForeignKey("TipoMaterialesId");

                    b.Navigation("TipoMateriales");
                });
#pragma warning restore 612, 618
        }
    }
}
